### ISSUE TITLE
Add TypeScript definition

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/alfy#127]
If anyone wants to contribute, keep this in mind:

- It should adhere to https://github.com/sindresorhus/typescript-definition-style-guide
- You should have a lot of TypeScript experience.
- The pull request should be high-quality. Not sloppy.
- Docs can be copy-pasted from the readme.

**Comment by jopemachine** [comment]
May I ask if I could take on this?

Here is my [draft](https://github.com/jopemachine/alfy/blob/Add-types/index.d.ts) though I'm not sure all the interface names are enough intuitive.

I'd appreciate it if you could check and tell me if there's anything lacking.

Note:

* The descriptions of attributes of ScriptFilterItem are be copied from [JSON script filter format](https://www.alfredapp.com/help/workflows/inputs/script-filter/json/), and the other comments were copied from alfy READMD.

* Since there is no type declarations in the [cache-conf](https://github.com/SamVerschueren/cache-conf), I also typed it in here though I'm not sure this type should be here.

* I excluded `action` from `ScriptFilterItem` because it is not implemented yet. (According to this [page](https://www.alfredapp.com/help/workflows/inputs/script-filter/json/),  it is going to be introduced in Alfred 4.5)

I appreciate for always providing and maintaining lots of awesome libraries.

**Comment by sindresorhus** [comment]
> May I ask if I could take on this?

Sure, do a pull request. It's easier to give feedback directly then.

**Comment by sindresorhus** [comment]
> Since there is no type declarations in the cache-conf, I also typed it in here though I'm not sure this type should be here.

Maybe do a pull request to add types to that package? Link to it here and I'll ping the maintainer to review it.

**Comment by sindresorhus** [comment]
> I've excluded action attritube from ScriptFilterItem because it is not implemented in Alfred yet. (According to this page, it is going to be introduced in Alfred 4.5)

Add it commented out with a todo comment to enable it when Alfred 4.5 is out.

**Comment by jopemachine** [comment]
Thanks, I made a [PR](https://github.com/sindresorhus/alfy/pull/138)
