### ISSUE TITLE
Add `maxAge` option for `alfy.cache`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/alfy#3]
// @SamVerschueren

**Comment by SamVerschueren** [comment]
Should we add a `maxAge` option in `Conf` and just pass this through?

The reason I'm asking is because we have to keep track of a timestamp. So the data provided to `alfy.cache.set` should be wrapped in another object.

```js
alfy.cache.set('foo', {foo: 'bar'}, {maxAge: 300000});
```

Internally this will be mapped to something like this

```json
{
    "timestamp": 1468228995000,
    "data": {
        "foo": "bar"
    }
}
```

When asking for the `foo` data, we don't want the wrapped structure back, we want the internal `data` object back.

So either we overwrite `alfy.cache.set` and `alfy.cache.get` or we implement this in `conf`.

**Comment by sindresorhus** [comment]
I think `maxAge` is outside the scope of `conf`.
